/*
 * DegreesInfoPanel.java
 *
 * Created on July 1, 2005, 3:05 PM
 */

package ika.gui;

import ika.gui.*;
import ika.map.tools.*;
import com.jhlabs.map.proj.Projection;
import ika.utils.CoordinateFormatter;
import java.awt.GraphicsConfiguration;
import java.awt.geom.AffineTransform;
import java.awt.geom.Point2D;
import java.text.*;

/**
 *
 * @author  Bernhard Jenny, Institute of Cartography, ETH Zurich.
 */
public class DegreesInfoPanel extends javax.swing.JPanel
        implements MapToolMouseMotionListener {
    
    private Projection projection;
    
    private static final DecimalFormat lonFormat =
            new DecimalFormat("##0.00\u00B0E;##0.00\u00B0W");
    private static final DecimalFormat latFormat =
            new DecimalFormat("##0.00\u00B0N;##0.00\u00B0S");
    static {
        DecimalFormatSymbols dfs = lonFormat.getDecimalFormatSymbols();
        dfs.setNaN("-");
        dfs.setInfinity("-");
        lonFormat.setDecimalFormatSymbols(dfs);
        dfs = latFormat.getDecimalFormatSymbols();
        dfs.setNaN("-");
        dfs.setInfinity("-");
        latFormat.setDecimalFormatSymbols(dfs);
    }
    
    /**
     * Creates new form DegreesInfoPanel
     */
    public DegreesInfoPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lonTextLabel = new javax.swing.JLabel();
        lonCoordLabel = new javax.swing.JLabel();
        latTextLabel = new javax.swing.JLabel();
        latCoordLabel = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(120, 26));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 26));
        lonTextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        lonTextLabel.setText("Lon:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(lonTextLabel, gridBagConstraints);

        lonCoordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        lonCoordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lonCoordLabel.setMinimumSize(new java.awt.Dimension(60, 13));
        lonCoordLabel.setPreferredSize(new java.awt.Dimension(60, 13));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanel1.add(lonCoordLabel, gridBagConstraints);

        latTextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        latTextLabel.setText("Lat:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(latTextLabel, gridBagConstraints);

        latCoordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        latCoordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        latCoordLabel.setMinimumSize(new java.awt.Dimension(55, 13));
        latCoordLabel.setPreferredSize(new java.awt.Dimension(55, 13));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanel1.add(latCoordLabel, gridBagConstraints);

        add(jPanel1);

    }// </editor-fold>//GEN-END:initComponents
    
    protected void updateCoordinates(java.awt.geom.Point2D.Double point,
            ika.gui.MapComponent mapComponent) {

        if (point == null || this.projection == null || !this.projection.hasInverse()) {
            this.lonCoordLabel.setText("-");
            this.latCoordLabel.setText("-");
        } else {
            Point2D.Double dst = new Point2D.Double();
            try {
                this.projection.inverseTransform(point, dst);
            } catch (Exception e) {
                this.lonCoordLabel.setText("-");
                this.latCoordLabel.setText("-");
                return;
            }
            this.lonCoordLabel.setText(lonFormat.format(dst.x));
            this.latCoordLabel.setText(latFormat.format(dst.y));
        }
    }
    
    public void mouseMoved(java.awt.geom.Point2D.Double point,
            ika.gui.MapComponent mapComponent) {
        this.updateCoordinates(point,mapComponent);
    }
    
    public void registerWithMapComponent(MapComponent mapComponent) {
        mapComponent.addMouseMotionListener(this);
    }

    public Projection getProjection() {
        return projection;
    }

    public void setProjection(Projection projection) {
        this.projection = projection;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JLabel latCoordLabel;
    private javax.swing.JLabel latTextLabel;
    protected javax.swing.JLabel lonCoordLabel;
    private javax.swing.JLabel lonTextLabel;
    // End of variables declaration//GEN-END:variables
    
}
