/*
 * ListDialog.java
 *
 * Created on Jul 8, 2009, 12:34:28 PM
 */
package ika.gui;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 * An JOptionPane showing a list of options that is closed when the user double
 * clicks an item in the list.
 * @author jenny
 */
public class ListDialog extends javax.swing.JPanel {

    public static final String SELECTION_CHANGED_PROPERTY = "list selection changed";

    /** Creates new form ListDialog */
    public ListDialog() {
        initComponents();
    }

    public ListDialog(String message) {
        initComponents();
        messageLabel.setText(message);
    }

    public void setMessage(String message) {
        messageLabel.setText(message);
    }

    public Object showDialog(Component parentComponent,
            String title,
            Object[] options) {
        return this.showDialog(parentComponent,
                title,
                JOptionPane.QUESTION_MESSAGE,
                JOptionPane.OK_CANCEL_OPTION,
                options);
    }

    public Object showDialog(Component parentComponent,
            String title,
            int messageType,
            int optionType,
            Object[] options) {

        DefaultListModel projListModel = new DefaultListModel();
        for (int i = 0; i < options.length; i++) {
            projListModel.addElement(options[i]);
        }
        list.setModel(projListModel);

        final JOptionPane pane = new JOptionPane(this, messageType, optionType);
        final JDialog dialog = pane.createDialog(parentComponent, title);

        // add mouse listener that will close the dialog when a list item is
        // double clicked
        MouseListener mouseListener = new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList) (evt.getSource());
                int index = list.locationToIndex(evt.getPoint());
                list.ensureIndexIsVisible(index);

                // close dialog on double-click
                if (evt.getClickCount() == 2) {
                    pane.setValue(new Integer(JOptionPane.OK_OPTION));
                    dialog.setVisible(false);
                }
            }
        };
        list.addMouseListener(mouseListener);
        dialog.setVisible(true);
        list.removeMouseListener(mouseListener);

        int dialogRes = ((Integer) (pane.getValue())).intValue();
        if (dialogRes != JOptionPane.OK_OPTION) {
            return null;
        }

        return list.getSelectedValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        messageLabel = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList();

        setLayout(new java.awt.GridBagLayout());

        messageLabel.setText("Choose an option:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(messageLabel, gridBagConstraints);

        listScrollPane.setMinimumSize(new java.awt.Dimension(250, 300));
        listScrollPane.setPreferredSize(new java.awt.Dimension(250, 300));

        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        listScrollPane.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(listScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        boolean isAdjusting = evt.getValueIsAdjusting();
        if (!isAdjusting) {
            firePropertyChange(SELECTION_CHANGED_PROPERTY, null, list.getSelectedValues());
        }
    }//GEN-LAST:event_listValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList list;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
